### ISSUE TITLE
dropcap_image read incorrectly by screenreader 

### ISSUE THREAD

**Issue by mundorfd** [mundorfd/LMS-HTML#1]
reads "W" elcome with the screenreader. I was able to add a screenreader only "Welcome" that isn't visible on the page. If I could somehow make 

`<span style="display: block; float: left; width: 125px; height: 90px; margin-top: 5px; padding-right: 8px; text-indent: -9000px; background-image: url('images/w.png'); background-repeat: no-repeat;">W</span>elcome` 

visible, but not read this would work.

**Comment by pchambers-osu** [comment]
Can we add `aria-hidden="true"` to the entire span?

**Comment by mundorfd** [comment]
It seems that ReadSpeaker is reading even with this parameter. Try this: `<p><span aria-hidden="true">Hi Phil</span></p>` @pchambers-osu

**Comment by pchambers-osu** [comment]
@mundorfd Replacing `aria-hidden="true"` with `class="rs_skip"` seems to make it work, unless you specifically highlight the text you want to test. If you look at the page now and let it read it all, it will skip the "Hi Phil" text.

**Comment by mundorfd** [comment]
`class="rs_skip"` resolves if whole page is read, not with selected text.
